version: 0.2

phases:
  build:
    commands:
      - chmod 744 gradlew
      - ./gradlew build
artifacts:
  files:
    - build/libs/cdk-manual-test-spring-boot-0.1.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes
